/* AlsongAPIService1SoapProxy.h
   Generated by gSOAP 2.8.21 from alsongapi.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef AlsongAPIService1SoapProxy_H
#define AlsongAPIService1SoapProxy_H
#include "AlsongAPIH.h"

class SOAP_CMAC Service1SoapProxy : public soap
{ public:
	/// Endpoint URL of service 'Service1SoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in alsongapi.h (non-static)
	/// Constructor
	Service1SoapProxy();
	/// Construct from another engine state
	Service1SoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	Service1SoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	Service1SoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	Service1SoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	Service1SoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~Service1SoapProxy();
	/// Initializer used by constructors
	virtual	void Service1SoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetMurekaInfo' (returns error code or SOAP_OK)
	virtual	int GetMurekaInfo(_ns1__GetMurekaInfo *ns1__GetMurekaInfo, _ns1__GetMurekaInfoResponse &ns1__GetMurekaInfoResponse) { return this->GetMurekaInfo(NULL, NULL, ns1__GetMurekaInfo, ns1__GetMurekaInfoResponse); }
	virtual	int GetMurekaInfo(const char *endpoint, const char *soap_action, _ns1__GetMurekaInfo *ns1__GetMurekaInfo, _ns1__GetMurekaInfoResponse &ns1__GetMurekaInfoResponse);

	/// Web service operation 'GetSyncLyricBySearch' (returns error code or SOAP_OK)
	virtual	int GetSyncLyricBySearch(_ns1__GetSyncLyricBySearch *ns1__GetSyncLyricBySearch, _ns1__GetSyncLyricBySearchResponse &ns1__GetSyncLyricBySearchResponse) { return this->GetSyncLyricBySearch(NULL, NULL, ns1__GetSyncLyricBySearch, ns1__GetSyncLyricBySearchResponse); }
	virtual	int GetSyncLyricBySearch(const char *endpoint, const char *soap_action, _ns1__GetSyncLyricBySearch *ns1__GetSyncLyricBySearch, _ns1__GetSyncLyricBySearchResponse &ns1__GetSyncLyricBySearchResponse);

	/// Web service operation 'SetLinkLyric' (returns error code or SOAP_OK)
	virtual	int SetLinkLyric(_ns1__SetLinkLyric *ns1__SetLinkLyric, _ns1__SetLinkLyricResponse &ns1__SetLinkLyricResponse) { return this->SetLinkLyric(NULL, NULL, ns1__SetLinkLyric, ns1__SetLinkLyricResponse); }
	virtual	int SetLinkLyric(const char *endpoint, const char *soap_action, _ns1__SetLinkLyric *ns1__SetLinkLyric, _ns1__SetLinkLyricResponse &ns1__SetLinkLyricResponse);

	/// Web service operation 'GetResembleLyric2' (returns error code or SOAP_OK)
	virtual	int GetResembleLyric2(_ns1__GetResembleLyric2 *ns1__GetResembleLyric2, _ns1__GetResembleLyric2Response &ns1__GetResembleLyric2Response) { return this->GetResembleLyric2(NULL, NULL, ns1__GetResembleLyric2, ns1__GetResembleLyric2Response); }
	virtual	int GetResembleLyric2(const char *endpoint, const char *soap_action, _ns1__GetResembleLyric2 *ns1__GetResembleLyric2, _ns1__GetResembleLyric2Response &ns1__GetResembleLyric2Response);

	/// Web service operation 'GetResembleLyric3' (returns error code or SOAP_OK)
	virtual	int GetResembleLyric3(_ns1__GetResembleLyric3 *ns1__GetResembleLyric3, _ns1__GetResembleLyric3Response &ns1__GetResembleLyric3Response) { return this->GetResembleLyric3(NULL, NULL, ns1__GetResembleLyric3, ns1__GetResembleLyric3Response); }
	virtual	int GetResembleLyric3(const char *endpoint, const char *soap_action, _ns1__GetResembleLyric3 *ns1__GetResembleLyric3, _ns1__GetResembleLyric3Response &ns1__GetResembleLyric3Response);

	/// Web service operation 'GetResembleLyric2Count' (returns error code or SOAP_OK)
	virtual	int GetResembleLyric2Count(_ns1__GetResembleLyric2Count *ns1__GetResembleLyric2Count, _ns1__GetResembleLyric2CountResponse &ns1__GetResembleLyric2CountResponse) { return this->GetResembleLyric2Count(NULL, NULL, ns1__GetResembleLyric2Count, ns1__GetResembleLyric2CountResponse); }
	virtual	int GetResembleLyric2Count(const char *endpoint, const char *soap_action, _ns1__GetResembleLyric2Count *ns1__GetResembleLyric2Count, _ns1__GetResembleLyric2CountResponse &ns1__GetResembleLyric2CountResponse);

	/// Web service operation 'GetResembleLyric2CountTest' (returns error code or SOAP_OK)
	virtual	int GetResembleLyric2CountTest(_ns1__GetResembleLyric2CountTest *ns1__GetResembleLyric2CountTest, _ns1__GetResembleLyric2CountTestResponse &ns1__GetResembleLyric2CountTestResponse) { return this->GetResembleLyric2CountTest(NULL, NULL, ns1__GetResembleLyric2CountTest, ns1__GetResembleLyric2CountTestResponse); }
	virtual	int GetResembleLyric2CountTest(const char *endpoint, const char *soap_action, _ns1__GetResembleLyric2CountTest *ns1__GetResembleLyric2CountTest, _ns1__GetResembleLyric2CountTestResponse &ns1__GetResembleLyric2CountTestResponse);

	/// Web service operation 'UploadLyric' (returns error code or SOAP_OK)
	virtual	int UploadLyric(_ns1__UploadLyric *ns1__UploadLyric, _ns1__UploadLyricResponse &ns1__UploadLyricResponse) { return this->UploadLyric(NULL, NULL, ns1__UploadLyric, ns1__UploadLyricResponse); }
	virtual	int UploadLyric(const char *endpoint, const char *soap_action, _ns1__UploadLyric *ns1__UploadLyric, _ns1__UploadLyricResponse &ns1__UploadLyricResponse);

	/// Web service operation 'ReportFaultLyricWithComment' (returns error code or SOAP_OK)
	virtual	int ReportFaultLyricWithComment(_ns1__ReportFaultLyricWithComment *ns1__ReportFaultLyricWithComment, _ns1__ReportFaultLyricWithCommentResponse &ns1__ReportFaultLyricWithCommentResponse) { return this->ReportFaultLyricWithComment(NULL, NULL, ns1__ReportFaultLyricWithComment, ns1__ReportFaultLyricWithCommentResponse); }
	virtual	int ReportFaultLyricWithComment(const char *endpoint, const char *soap_action, _ns1__ReportFaultLyricWithComment *ns1__ReportFaultLyricWithComment, _ns1__ReportFaultLyricWithCommentResponse &ns1__ReportFaultLyricWithCommentResponse);

	/// Web service operation 'ReportFaultLyric2' (returns error code or SOAP_OK)
	virtual	int ReportFaultLyric2(_ns1__ReportFaultLyric2 *ns1__ReportFaultLyric2, _ns1__ReportFaultLyric2Response &ns1__ReportFaultLyric2Response) { return this->ReportFaultLyric2(NULL, NULL, ns1__ReportFaultLyric2, ns1__ReportFaultLyric2Response); }
	virtual	int ReportFaultLyric2(const char *endpoint, const char *soap_action, _ns1__ReportFaultLyric2 *ns1__ReportFaultLyric2, _ns1__ReportFaultLyric2Response &ns1__ReportFaultLyric2Response);

	/// Web service operation 'ReportRecommendationLyric' (returns error code or SOAP_OK)
	virtual	int ReportRecommendationLyric(_ns1__ReportRecommendationLyric *ns1__ReportRecommendationLyric, _ns1__ReportRecommendationLyricResponse &ns1__ReportRecommendationLyricResponse) { return this->ReportRecommendationLyric(NULL, NULL, ns1__ReportRecommendationLyric, ns1__ReportRecommendationLyricResponse); }
	virtual	int ReportRecommendationLyric(const char *endpoint, const char *soap_action, _ns1__ReportRecommendationLyric *ns1__ReportRecommendationLyric, _ns1__ReportRecommendationLyricResponse &ns1__ReportRecommendationLyricResponse);

	/// Web service operation 'IsReportedRecommendationLyric' (returns error code or SOAP_OK)
	virtual	int IsReportedRecommendationLyric(_ns1__IsReportedRecommendationLyric *ns1__IsReportedRecommendationLyric, _ns1__IsReportedRecommendationLyricResponse &ns1__IsReportedRecommendationLyricResponse) { return this->IsReportedRecommendationLyric(NULL, NULL, ns1__IsReportedRecommendationLyric, ns1__IsReportedRecommendationLyricResponse); }
	virtual	int IsReportedRecommendationLyric(const char *endpoint, const char *soap_action, _ns1__IsReportedRecommendationLyric *ns1__IsReportedRecommendationLyric, _ns1__IsReportedRecommendationLyricResponse &ns1__IsReportedRecommendationLyricResponse);

	/// Web service operation 'IsReportedFaultLyric' (returns error code or SOAP_OK)
	virtual	int IsReportedFaultLyric(_ns1__IsReportedFaultLyric *ns1__IsReportedFaultLyric, _ns1__IsReportedFaultLyricResponse &ns1__IsReportedFaultLyricResponse) { return this->IsReportedFaultLyric(NULL, NULL, ns1__IsReportedFaultLyric, ns1__IsReportedFaultLyricResponse); }
	virtual	int IsReportedFaultLyric(const char *endpoint, const char *soap_action, _ns1__IsReportedFaultLyric *ns1__IsReportedFaultLyric, _ns1__IsReportedFaultLyricResponse &ns1__IsReportedFaultLyricResponse);

	/// Web service operation 'GetLyric3' (returns error code or SOAP_OK)
	virtual	int GetLyric3(_ns1__GetLyric3 *ns1__GetLyric3, _ns1__GetLyric3Response &ns1__GetLyric3Response) { return this->GetLyric3(NULL, NULL, ns1__GetLyric3, ns1__GetLyric3Response); }
	virtual	int GetLyric3(const char *endpoint, const char *soap_action, _ns1__GetLyric3 *ns1__GetLyric3, _ns1__GetLyric3Response &ns1__GetLyric3Response);

	/// Web service operation 'GetLyric4' (returns error code or SOAP_OK)
	virtual	int GetLyric4(_ns1__GetLyric4 *ns1__GetLyric4, _ns1__GetLyric4Response &ns1__GetLyric4Response) { return this->GetLyric4(NULL, NULL, ns1__GetLyric4, ns1__GetLyric4Response); }
	virtual	int GetLyric4(const char *endpoint, const char *soap_action, _ns1__GetLyric4 *ns1__GetLyric4, _ns1__GetLyric4Response &ns1__GetLyric4Response);

	/// Web service operation 'GetLyric5' (returns error code or SOAP_OK)
	virtual	int GetLyric5(_ns1__GetLyric5 *ns1__GetLyric5, _ns1__GetLyric5Response &ns1__GetLyric5Response) { return this->GetLyric5(NULL, NULL, ns1__GetLyric5, ns1__GetLyric5Response); }
	virtual	int GetLyric5(const char *endpoint, const char *soap_action, _ns1__GetLyric5 *ns1__GetLyric5, _ns1__GetLyric5Response &ns1__GetLyric5Response);

	/// Web service operation 'GetLyric6' (returns error code or SOAP_OK)
	virtual	int GetLyric6(_ns1__GetLyric6 *ns1__GetLyric6, _ns1__GetLyric6Response &ns1__GetLyric6Response) { return this->GetLyric6(NULL, NULL, ns1__GetLyric6, ns1__GetLyric6Response); }
	virtual	int GetLyric6(const char *endpoint, const char *soap_action, _ns1__GetLyric6 *ns1__GetLyric6, _ns1__GetLyric6Response &ns1__GetLyric6Response);

	/// Web service operation 'GetLyric7' (returns error code or SOAP_OK)
	virtual	int GetLyric7(_ns1__GetLyric7 *ns1__GetLyric7, _ns1__GetLyric7Response &ns1__GetLyric7Response) { return this->GetLyric7(NULL, NULL, ns1__GetLyric7, ns1__GetLyric7Response); }
	virtual	int GetLyric7(const char *endpoint, const char *soap_action, _ns1__GetLyric7 *ns1__GetLyric7, _ns1__GetLyric7Response &ns1__GetLyric7Response);

	/// Web service operation 'GetLyric8' (returns error code or SOAP_OK)
	virtual	int GetLyric8(_ns1__GetLyric8 *ns1__GetLyric8, _ns1__GetLyric8Response &ns1__GetLyric8Response) { return this->GetLyric8(NULL, NULL, ns1__GetLyric8, ns1__GetLyric8Response); }
	virtual	int GetLyric8(const char *endpoint, const char *soap_action, _ns1__GetLyric8 *ns1__GetLyric8, _ns1__GetLyric8Response &ns1__GetLyric8Response);

	/// Web service operation 'GetSongID' (returns error code or SOAP_OK)
	virtual	int GetSongID(_ns1__GetSongID *ns1__GetSongID, _ns1__GetSongIDResponse &ns1__GetSongIDResponse) { return this->GetSongID(NULL, NULL, ns1__GetSongID, ns1__GetSongIDResponse); }
	virtual	int GetSongID(const char *endpoint, const char *soap_action, _ns1__GetSongID *ns1__GetSongID, _ns1__GetSongIDResponse &ns1__GetSongIDResponse);

	/// Web service operation 'AdminGetLyricList' (returns error code or SOAP_OK)
	virtual	int AdminGetLyricList(_ns1__AdminGetLyricList *ns1__AdminGetLyricList, _ns1__AdminGetLyricListResponse &ns1__AdminGetLyricListResponse) { return this->AdminGetLyricList(NULL, NULL, ns1__AdminGetLyricList, ns1__AdminGetLyricListResponse); }
	virtual	int AdminGetLyricList(const char *endpoint, const char *soap_action, _ns1__AdminGetLyricList *ns1__AdminGetLyricList, _ns1__AdminGetLyricListResponse &ns1__AdminGetLyricListResponse);

	/// Web service operation 'AdminGetLyricListByID' (returns error code or SOAP_OK)
	virtual	int AdminGetLyricListByID(_ns1__AdminGetLyricListByID *ns1__AdminGetLyricListByID, _ns1__AdminGetLyricListByIDResponse &ns1__AdminGetLyricListByIDResponse) { return this->AdminGetLyricListByID(NULL, NULL, ns1__AdminGetLyricListByID, ns1__AdminGetLyricListByIDResponse); }
	virtual	int AdminGetLyricListByID(const char *endpoint, const char *soap_action, _ns1__AdminGetLyricListByID *ns1__AdminGetLyricListByID, _ns1__AdminGetLyricListByIDResponse &ns1__AdminGetLyricListByIDResponse);

	/// Web service operation 'AdminGetReportFaultList' (returns error code or SOAP_OK)
	virtual	int AdminGetReportFaultList(_ns1__AdminGetReportFaultList *ns1__AdminGetReportFaultList, _ns1__AdminGetReportFaultListResponse &ns1__AdminGetReportFaultListResponse) { return this->AdminGetReportFaultList(NULL, NULL, ns1__AdminGetReportFaultList, ns1__AdminGetReportFaultListResponse); }
	virtual	int AdminGetReportFaultList(const char *endpoint, const char *soap_action, _ns1__AdminGetReportFaultList *ns1__AdminGetReportFaultList, _ns1__AdminGetReportFaultListResponse &ns1__AdminGetReportFaultListResponse);

	/// Web service operation 'AdminGetModifyList' (returns error code or SOAP_OK)
	virtual	int AdminGetModifyList(_ns1__AdminGetModifyList *ns1__AdminGetModifyList, _ns1__AdminGetModifyListResponse &ns1__AdminGetModifyListResponse) { return this->AdminGetModifyList(NULL, NULL, ns1__AdminGetModifyList, ns1__AdminGetModifyListResponse); }
	virtual	int AdminGetModifyList(const char *endpoint, const char *soap_action, _ns1__AdminGetModifyList *ns1__AdminGetModifyList, _ns1__AdminGetModifyListResponse &ns1__AdminGetModifyListResponse);

	/// Web service operation 'AdminGetRegisterList' (returns error code or SOAP_OK)
	virtual	int AdminGetRegisterList(_ns1__AdminGetRegisterList *ns1__AdminGetRegisterList, _ns1__AdminGetRegisterListResponse &ns1__AdminGetRegisterListResponse) { return this->AdminGetRegisterList(NULL, NULL, ns1__AdminGetRegisterList, ns1__AdminGetRegisterListResponse); }
	virtual	int AdminGetRegisterList(const char *endpoint, const char *soap_action, _ns1__AdminGetRegisterList *ns1__AdminGetRegisterList, _ns1__AdminGetRegisterListResponse &ns1__AdminGetRegisterListResponse);

	/// Web service operation 'MemberAddMember' (returns error code or SOAP_OK)
	virtual	int MemberAddMember(_ns1__MemberAddMember *ns1__MemberAddMember, _ns1__MemberAddMemberResponse &ns1__MemberAddMemberResponse) { return this->MemberAddMember(NULL, NULL, ns1__MemberAddMember, ns1__MemberAddMemberResponse); }
	virtual	int MemberAddMember(const char *endpoint, const char *soap_action, _ns1__MemberAddMember *ns1__MemberAddMember, _ns1__MemberAddMemberResponse &ns1__MemberAddMemberResponse);

	/// Web service operation 'MemberModifyMember' (returns error code or SOAP_OK)
	virtual	int MemberModifyMember(_ns1__MemberModifyMember *ns1__MemberModifyMember, _ns1__MemberModifyMemberResponse &ns1__MemberModifyMemberResponse) { return this->MemberModifyMember(NULL, NULL, ns1__MemberModifyMember, ns1__MemberModifyMemberResponse); }
	virtual	int MemberModifyMember(const char *endpoint, const char *soap_action, _ns1__MemberModifyMember *ns1__MemberModifyMember, _ns1__MemberModifyMemberResponse &ns1__MemberModifyMemberResponse);

	/// Web service operation 'MemberRemoveMember' (returns error code or SOAP_OK)
	virtual	int MemberRemoveMember(_ns1__MemberRemoveMember *ns1__MemberRemoveMember, _ns1__MemberRemoveMemberResponse &ns1__MemberRemoveMemberResponse) { return this->MemberRemoveMember(NULL, NULL, ns1__MemberRemoveMember, ns1__MemberRemoveMemberResponse); }
	virtual	int MemberRemoveMember(const char *endpoint, const char *soap_action, _ns1__MemberRemoveMember *ns1__MemberRemoveMember, _ns1__MemberRemoveMemberResponse &ns1__MemberRemoveMemberResponse);

	/// Web service operation 'MemberLogin' (returns error code or SOAP_OK)
	virtual	int MemberLogin(_ns1__MemberLogin *ns1__MemberLogin, _ns1__MemberLoginResponse &ns1__MemberLoginResponse) { return this->MemberLogin(NULL, NULL, ns1__MemberLogin, ns1__MemberLoginResponse); }
	virtual	int MemberLogin(const char *endpoint, const char *soap_action, _ns1__MemberLogin *ns1__MemberLogin, _ns1__MemberLoginResponse &ns1__MemberLoginResponse);

	/// Web service operation 'MemberLogout' (returns error code or SOAP_OK)
	virtual	int MemberLogout(_ns1__MemberLogout *ns1__MemberLogout, _ns1__MemberLogoutResponse &ns1__MemberLogoutResponse) { return this->MemberLogout(NULL, NULL, ns1__MemberLogout, ns1__MemberLogoutResponse); }
	virtual	int MemberLogout(const char *endpoint, const char *soap_action, _ns1__MemberLogout *ns1__MemberLogout, _ns1__MemberLogoutResponse &ns1__MemberLogoutResponse);

	/// Web service operation 'MemberApplyRegistration' (returns error code or SOAP_OK)
	virtual	int MemberApplyRegistration(_ns1__MemberApplyRegistration *ns1__MemberApplyRegistration, _ns1__MemberApplyRegistrationResponse &ns1__MemberApplyRegistrationResponse) { return this->MemberApplyRegistration(NULL, NULL, ns1__MemberApplyRegistration, ns1__MemberApplyRegistrationResponse); }
	virtual	int MemberApplyRegistration(const char *endpoint, const char *soap_action, _ns1__MemberApplyRegistration *ns1__MemberApplyRegistration, _ns1__MemberApplyRegistrationResponse &ns1__MemberApplyRegistrationResponse);

	/// Web service operation 'MemberModifyMemberLicense' (returns error code or SOAP_OK)
	virtual	int MemberModifyMemberLicense(_ns1__MemberModifyMemberLicense *ns1__MemberModifyMemberLicense, _ns1__MemberModifyMemberLicenseResponse &ns1__MemberModifyMemberLicenseResponse) { return this->MemberModifyMemberLicense(NULL, NULL, ns1__MemberModifyMemberLicense, ns1__MemberModifyMemberLicenseResponse); }
	virtual	int MemberModifyMemberLicense(const char *endpoint, const char *soap_action, _ns1__MemberModifyMemberLicense *ns1__MemberModifyMemberLicense, _ns1__MemberModifyMemberLicenseResponse &ns1__MemberModifyMemberLicenseResponse);

	/// Web service operation 'MemberGetMemberList' (returns error code or SOAP_OK)
	virtual	int MemberGetMemberList(_ns1__MemberGetMemberList *ns1__MemberGetMemberList, _ns1__MemberGetMemberListResponse &ns1__MemberGetMemberListResponse) { return this->MemberGetMemberList(NULL, NULL, ns1__MemberGetMemberList, ns1__MemberGetMemberListResponse); }
	virtual	int MemberGetMemberList(const char *endpoint, const char *soap_action, _ns1__MemberGetMemberList *ns1__MemberGetMemberList, _ns1__MemberGetMemberListResponse &ns1__MemberGetMemberListResponse);

	/// Web service operation 'MemberGetMemberLicenseList' (returns error code or SOAP_OK)
	virtual	int MemberGetMemberLicenseList(_ns1__MemberGetMemberLicenseList *ns1__MemberGetMemberLicenseList, _ns1__MemberGetMemberLicenseListResponse &ns1__MemberGetMemberLicenseListResponse) { return this->MemberGetMemberLicenseList(NULL, NULL, ns1__MemberGetMemberLicenseList, ns1__MemberGetMemberLicenseListResponse); }
	virtual	int MemberGetMemberLicenseList(const char *endpoint, const char *soap_action, _ns1__MemberGetMemberLicenseList *ns1__MemberGetMemberLicenseList, _ns1__MemberGetMemberLicenseListResponse &ns1__MemberGetMemberLicenseListResponse);

	/// Web service operation 'AdminDeleteRecord' (returns error code or SOAP_OK)
	virtual	int AdminDeleteRecord(_ns1__AdminDeleteRecord *ns1__AdminDeleteRecord, _ns1__AdminDeleteRecordResponse &ns1__AdminDeleteRecordResponse) { return this->AdminDeleteRecord(NULL, NULL, ns1__AdminDeleteRecord, ns1__AdminDeleteRecordResponse); }
	virtual	int AdminDeleteRecord(const char *endpoint, const char *soap_action, _ns1__AdminDeleteRecord *ns1__AdminDeleteRecord, _ns1__AdminDeleteRecordResponse &ns1__AdminDeleteRecordResponse);

	/// Web service operation 'AdminAdmitModifyLyric' (returns error code or SOAP_OK)
	virtual	int AdminAdmitModifyLyric(_ns1__AdminAdmitModifyLyric *ns1__AdminAdmitModifyLyric, _ns1__AdminAdmitModifyLyricResponse &ns1__AdminAdmitModifyLyricResponse) { return this->AdminAdmitModifyLyric(NULL, NULL, ns1__AdminAdmitModifyLyric, ns1__AdminAdmitModifyLyricResponse); }
	virtual	int AdminAdmitModifyLyric(const char *endpoint, const char *soap_action, _ns1__AdminAdmitModifyLyric *ns1__AdminAdmitModifyLyric, _ns1__AdminAdmitModifyLyricResponse &ns1__AdminAdmitModifyLyricResponse);

	/// Web service operation 'AdminReportBlackList' (returns error code or SOAP_OK)
	virtual	int AdminReportBlackList(_ns1__AdminReportBlackList *ns1__AdminReportBlackList, _ns1__AdminReportBlackListResponse &ns1__AdminReportBlackListResponse) { return this->AdminReportBlackList(NULL, NULL, ns1__AdminReportBlackList, ns1__AdminReportBlackListResponse); }
	virtual	int AdminReportBlackList(const char *endpoint, const char *soap_action, _ns1__AdminReportBlackList *ns1__AdminReportBlackList, _ns1__AdminReportBlackListResponse &ns1__AdminReportBlackListResponse);

	/// Web service operation 'AdminGetCountInRegister' (returns error code or SOAP_OK)
	virtual	int AdminGetCountInRegister(_ns1__AdminGetCountInRegister *ns1__AdminGetCountInRegister, _ns1__AdminGetCountInRegisterResponse &ns1__AdminGetCountInRegisterResponse) { return this->AdminGetCountInRegister(NULL, NULL, ns1__AdminGetCountInRegister, ns1__AdminGetCountInRegisterResponse); }
	virtual	int AdminGetCountInRegister(const char *endpoint, const char *soap_action, _ns1__AdminGetCountInRegister *ns1__AdminGetCountInRegister, _ns1__AdminGetCountInRegisterResponse &ns1__AdminGetCountInRegisterResponse);

	/// Web service operation 'AdminGetCountChecksum' (returns error code or SOAP_OK)
	virtual	int AdminGetCountChecksum(_ns1__AdminGetCountChecksum *ns1__AdminGetCountChecksum, _ns1__AdminGetCountChecksumResponse &ns1__AdminGetCountChecksumResponse) { return this->AdminGetCountChecksum(NULL, NULL, ns1__AdminGetCountChecksum, ns1__AdminGetCountChecksumResponse); }
	virtual	int AdminGetCountChecksum(const char *endpoint, const char *soap_action, _ns1__AdminGetCountChecksum *ns1__AdminGetCountChecksum, _ns1__AdminGetCountChecksumResponse &ns1__AdminGetCountChecksumResponse);

	/// Web service operation 'AdminGetCountLyric' (returns error code or SOAP_OK)
	virtual	int AdminGetCountLyric(_ns1__AdminGetCountLyric *ns1__AdminGetCountLyric, _ns1__AdminGetCountLyricResponse &ns1__AdminGetCountLyricResponse) { return this->AdminGetCountLyric(NULL, NULL, ns1__AdminGetCountLyric, ns1__AdminGetCountLyricResponse); }
	virtual	int AdminGetCountLyric(const char *endpoint, const char *soap_action, _ns1__AdminGetCountLyric *ns1__AdminGetCountLyric, _ns1__AdminGetCountLyricResponse &ns1__AdminGetCountLyricResponse);

	/// Web service operation 'AdminGetCountModify' (returns error code or SOAP_OK)
	virtual	int AdminGetCountModify(_ns1__AdminGetCountModify *ns1__AdminGetCountModify, _ns1__AdminGetCountModifyResponse &ns1__AdminGetCountModifyResponse) { return this->AdminGetCountModify(NULL, NULL, ns1__AdminGetCountModify, ns1__AdminGetCountModifyResponse); }
	virtual	int AdminGetCountModify(const char *endpoint, const char *soap_action, _ns1__AdminGetCountModify *ns1__AdminGetCountModify, _ns1__AdminGetCountModifyResponse &ns1__AdminGetCountModifyResponse);

	/// Web service operation 'AdminGetCountReport' (returns error code or SOAP_OK)
	virtual	int AdminGetCountReport(_ns1__AdminGetCountReport *ns1__AdminGetCountReport, _ns1__AdminGetCountReportResponse &ns1__AdminGetCountReportResponse) { return this->AdminGetCountReport(NULL, NULL, ns1__AdminGetCountReport, ns1__AdminGetCountReportResponse); }
	virtual	int AdminGetCountReport(const char *endpoint, const char *soap_action, _ns1__AdminGetCountReport *ns1__AdminGetCountReport, _ns1__AdminGetCountReportResponse &ns1__AdminGetCountReportResponse);

	/// Web service operation 'AdminGetAlbaStatistic' (returns error code or SOAP_OK)
	virtual	int AdminGetAlbaStatistic(_ns1__AdminGetAlbaStatistic *ns1__AdminGetAlbaStatistic, _ns1__AdminGetAlbaStatisticResponse &ns1__AdminGetAlbaStatisticResponse) { return this->AdminGetAlbaStatistic(NULL, NULL, ns1__AdminGetAlbaStatistic, ns1__AdminGetAlbaStatisticResponse); }
	virtual	int AdminGetAlbaStatistic(const char *endpoint, const char *soap_action, _ns1__AdminGetAlbaStatistic *ns1__AdminGetAlbaStatistic, _ns1__AdminGetAlbaStatisticResponse &ns1__AdminGetAlbaStatisticResponse);

	/// Web service operation 'CastUploadExMetaData' (returns error code or SOAP_OK)
	virtual	int CastUploadExMetaData(_ns1__CastUploadExMetaData *ns1__CastUploadExMetaData, _ns1__CastUploadExMetaDataResponse &ns1__CastUploadExMetaDataResponse) { return this->CastUploadExMetaData(NULL, NULL, ns1__CastUploadExMetaData, ns1__CastUploadExMetaDataResponse); }
	virtual	int CastUploadExMetaData(const char *endpoint, const char *soap_action, _ns1__CastUploadExMetaData *ns1__CastUploadExMetaData, _ns1__CastUploadExMetaDataResponse &ns1__CastUploadExMetaDataResponse);

	/// Web service operation 'CastUploadExMetaData2' (returns error code or SOAP_OK)
	virtual	int CastUploadExMetaData2(_ns1__CastUploadExMetaData2 *ns1__CastUploadExMetaData2, _ns1__CastUploadExMetaData2Response &ns1__CastUploadExMetaData2Response) { return this->CastUploadExMetaData2(NULL, NULL, ns1__CastUploadExMetaData2, ns1__CastUploadExMetaData2Response); }
	virtual	int CastUploadExMetaData2(const char *endpoint, const char *soap_action, _ns1__CastUploadExMetaData2 *ns1__CastUploadExMetaData2, _ns1__CastUploadExMetaData2Response &ns1__CastUploadExMetaData2Response);

	/// Web service operation 'CastUploadExMetaData3' (returns error code or SOAP_OK)
	virtual	int CastUploadExMetaData3(_ns1__CastUploadExMetaData3 *ns1__CastUploadExMetaData3, _ns1__CastUploadExMetaData3Response &ns1__CastUploadExMetaData3Response) { return this->CastUploadExMetaData3(NULL, NULL, ns1__CastUploadExMetaData3, ns1__CastUploadExMetaData3Response); }
	virtual	int CastUploadExMetaData3(const char *endpoint, const char *soap_action, _ns1__CastUploadExMetaData3 *ns1__CastUploadExMetaData3, _ns1__CastUploadExMetaData3Response &ns1__CastUploadExMetaData3Response);

	/// Web service operation 'CastRemoveExMetaData' (returns error code or SOAP_OK)
	virtual	int CastRemoveExMetaData(_ns1__CastRemoveExMetaData *ns1__CastRemoveExMetaData, _ns1__CastRemoveExMetaDataResponse &ns1__CastRemoveExMetaDataResponse) { return this->CastRemoveExMetaData(NULL, NULL, ns1__CastRemoveExMetaData, ns1__CastRemoveExMetaDataResponse); }
	virtual	int CastRemoveExMetaData(const char *endpoint, const char *soap_action, _ns1__CastRemoveExMetaData *ns1__CastRemoveExMetaData, _ns1__CastRemoveExMetaDataResponse &ns1__CastRemoveExMetaDataResponse);

	/// Web service operation 'CastGetExMetaData' (returns error code or SOAP_OK)
	virtual	int CastGetExMetaData(_ns1__CastGetExMetaData *ns1__CastGetExMetaData, _ns1__CastGetExMetaDataResponse &ns1__CastGetExMetaDataResponse) { return this->CastGetExMetaData(NULL, NULL, ns1__CastGetExMetaData, ns1__CastGetExMetaDataResponse); }
	virtual	int CastGetExMetaData(const char *endpoint, const char *soap_action, _ns1__CastGetExMetaData *ns1__CastGetExMetaData, _ns1__CastGetExMetaDataResponse &ns1__CastGetExMetaDataResponse);

	/// Web service operation 'CastGetExMetaDataList' (returns error code or SOAP_OK)
	virtual	int CastGetExMetaDataList(_ns1__CastGetExMetaDataList *ns1__CastGetExMetaDataList, _ns1__CastGetExMetaDataListResponse &ns1__CastGetExMetaDataListResponse) { return this->CastGetExMetaDataList(NULL, NULL, ns1__CastGetExMetaDataList, ns1__CastGetExMetaDataListResponse); }
	virtual	int CastGetExMetaDataList(const char *endpoint, const char *soap_action, _ns1__CastGetExMetaDataList *ns1__CastGetExMetaDataList, _ns1__CastGetExMetaDataListResponse &ns1__CastGetExMetaDataListResponse);

	/// Web service operation 'CastGetExMetaDataList2' (returns error code or SOAP_OK)
	virtual	int CastGetExMetaDataList2(_ns1__CastGetExMetaDataList2 *ns1__CastGetExMetaDataList2, _ns1__CastGetExMetaDataList2Response &ns1__CastGetExMetaDataList2Response) { return this->CastGetExMetaDataList2(NULL, NULL, ns1__CastGetExMetaDataList2, ns1__CastGetExMetaDataList2Response); }
	virtual	int CastGetExMetaDataList2(const char *endpoint, const char *soap_action, _ns1__CastGetExMetaDataList2 *ns1__CastGetExMetaDataList2, _ns1__CastGetExMetaDataList2Response &ns1__CastGetExMetaDataList2Response);

	/// Web service operation 'CastGetExMetaDataList3' (returns error code or SOAP_OK)
	virtual	int CastGetExMetaDataList3(_ns1__CastGetExMetaDataList3 *ns1__CastGetExMetaDataList3, _ns1__CastGetExMetaDataList3Response &ns1__CastGetExMetaDataList3Response) { return this->CastGetExMetaDataList3(NULL, NULL, ns1__CastGetExMetaDataList3, ns1__CastGetExMetaDataList3Response); }
	virtual	int CastGetExMetaDataList3(const char *endpoint, const char *soap_action, _ns1__CastGetExMetaDataList3 *ns1__CastGetExMetaDataList3, _ns1__CastGetExMetaDataList3Response &ns1__CastGetExMetaDataList3Response);

	/// Web service operation 'GetBroadcastingList' (returns error code or SOAP_OK)
	virtual	int GetBroadcastingList(_ns1__GetBroadcastingList *ns1__GetBroadcastingList, _ns1__GetBroadcastingListResponse &ns1__GetBroadcastingListResponse) { return this->GetBroadcastingList(NULL, NULL, ns1__GetBroadcastingList, ns1__GetBroadcastingListResponse); }
	virtual	int GetBroadcastingList(const char *endpoint, const char *soap_action, _ns1__GetBroadcastingList *ns1__GetBroadcastingList, _ns1__GetBroadcastingListResponse &ns1__GetBroadcastingListResponse);

	/// Web service operation 'GetBroadcastingList2' (returns error code or SOAP_OK)
	virtual	int GetBroadcastingList2(_ns1__GetBroadcastingList2 *ns1__GetBroadcastingList2, _ns1__GetBroadcastingList2Response &ns1__GetBroadcastingList2Response) { return this->GetBroadcastingList2(NULL, NULL, ns1__GetBroadcastingList2, ns1__GetBroadcastingList2Response); }
	virtual	int GetBroadcastingList2(const char *endpoint, const char *soap_action, _ns1__GetBroadcastingList2 *ns1__GetBroadcastingList2, _ns1__GetBroadcastingList2Response &ns1__GetBroadcastingList2Response);

	/// Web service operation 'UploadForeignLyric' (returns error code or SOAP_OK)
	virtual	int UploadForeignLyric(_ns1__UploadForeignLyric *ns1__UploadForeignLyric, _ns1__UploadForeignLyricResponse &ns1__UploadForeignLyricResponse) { return this->UploadForeignLyric(NULL, NULL, ns1__UploadForeignLyric, ns1__UploadForeignLyricResponse); }
	virtual	int UploadForeignLyric(const char *endpoint, const char *soap_action, _ns1__UploadForeignLyric *ns1__UploadForeignLyric, _ns1__UploadForeignLyricResponse &ns1__UploadForeignLyricResponse);

	/// Web service operation 'GetResembleLyricList' (returns error code or SOAP_OK)
	virtual	int GetResembleLyricList(_ns1__GetResembleLyricList *ns1__GetResembleLyricList, _ns1__GetResembleLyricListResponse &ns1__GetResembleLyricListResponse) { return this->GetResembleLyricList(NULL, NULL, ns1__GetResembleLyricList, ns1__GetResembleLyricListResponse); }
	virtual	int GetResembleLyricList(const char *endpoint, const char *soap_action, _ns1__GetResembleLyricList *ns1__GetResembleLyricList, _ns1__GetResembleLyricListResponse &ns1__GetResembleLyricListResponse);

	/// Web service operation 'GetResembleLyricList2' (returns error code or SOAP_OK)
	virtual	int GetResembleLyricList2(_ns1__GetResembleLyricList2 *ns1__GetResembleLyricList2, _ns1__GetResembleLyricList2Response &ns1__GetResembleLyricList2Response) { return this->GetResembleLyricList2(NULL, NULL, ns1__GetResembleLyricList2, ns1__GetResembleLyricList2Response); }
	virtual	int GetResembleLyricList2(const char *endpoint, const char *soap_action, _ns1__GetResembleLyricList2 *ns1__GetResembleLyricList2, _ns1__GetResembleLyricList2Response &ns1__GetResembleLyricList2Response);

	/// Web service operation 'GetLyricByID' (returns error code or SOAP_OK)
	virtual	int GetLyricByID(_ns1__GetLyricByID *ns1__GetLyricByID, _ns1__GetLyricByIDResponse &ns1__GetLyricByIDResponse) { return this->GetLyricByID(NULL, NULL, ns1__GetLyricByID, ns1__GetLyricByIDResponse); }
	virtual	int GetLyricByID(const char *endpoint, const char *soap_action, _ns1__GetLyricByID *ns1__GetLyricByID, _ns1__GetLyricByIDResponse &ns1__GetLyricByIDResponse);

	/// Web service operation 'GetLyricByID2' (returns error code or SOAP_OK)
	virtual	int GetLyricByID2(_ns1__GetLyricByID2 *ns1__GetLyricByID2, _ns1__GetLyricByID2Response &ns1__GetLyricByID2Response) { return this->GetLyricByID2(NULL, NULL, ns1__GetLyricByID2, ns1__GetLyricByID2Response); }
	virtual	int GetLyricByID2(const char *endpoint, const char *soap_action, _ns1__GetLyricByID2 *ns1__GetLyricByID2, _ns1__GetLyricByID2Response &ns1__GetLyricByID2Response);

	/// Web service operation 'AdminJPNGetRightsInfoByModifyID' (returns error code or SOAP_OK)
	virtual	int AdminJPNGetRightsInfoByModifyID(_ns1__AdminJPNGetRightsInfoByModifyID *ns1__AdminJPNGetRightsInfoByModifyID, _ns1__AdminJPNGetRightsInfoByModifyIDResponse &ns1__AdminJPNGetRightsInfoByModifyIDResponse) { return this->AdminJPNGetRightsInfoByModifyID(NULL, NULL, ns1__AdminJPNGetRightsInfoByModifyID, ns1__AdminJPNGetRightsInfoByModifyIDResponse); }
	virtual	int AdminJPNGetRightsInfoByModifyID(const char *endpoint, const char *soap_action, _ns1__AdminJPNGetRightsInfoByModifyID *ns1__AdminJPNGetRightsInfoByModifyID, _ns1__AdminJPNGetRightsInfoByModifyIDResponse &ns1__AdminJPNGetRightsInfoByModifyIDResponse);

	/// Web service operation 'AdminJPNGetRightsInfoByLyricID' (returns error code or SOAP_OK)
	virtual	int AdminJPNGetRightsInfoByLyricID(_ns1__AdminJPNGetRightsInfoByLyricID *ns1__AdminJPNGetRightsInfoByLyricID, _ns1__AdminJPNGetRightsInfoByLyricIDResponse &ns1__AdminJPNGetRightsInfoByLyricIDResponse) { return this->AdminJPNGetRightsInfoByLyricID(NULL, NULL, ns1__AdminJPNGetRightsInfoByLyricID, ns1__AdminJPNGetRightsInfoByLyricIDResponse); }
	virtual	int AdminJPNGetRightsInfoByLyricID(const char *endpoint, const char *soap_action, _ns1__AdminJPNGetRightsInfoByLyricID *ns1__AdminJPNGetRightsInfoByLyricID, _ns1__AdminJPNGetRightsInfoByLyricIDResponse &ns1__AdminJPNGetRightsInfoByLyricIDResponse);

	/// Web service operation 'AdminJPNSetRightsInfo' (returns error code or SOAP_OK)
	virtual	int AdminJPNSetRightsInfo(_ns1__AdminJPNSetRightsInfo *ns1__AdminJPNSetRightsInfo, _ns1__AdminJPNSetRightsInfoResponse &ns1__AdminJPNSetRightsInfoResponse) { return this->AdminJPNSetRightsInfo(NULL, NULL, ns1__AdminJPNSetRightsInfo, ns1__AdminJPNSetRightsInfoResponse); }
	virtual	int AdminJPNSetRightsInfo(const char *endpoint, const char *soap_action, _ns1__AdminJPNSetRightsInfo *ns1__AdminJPNSetRightsInfo, _ns1__AdminJPNSetRightsInfoResponse &ns1__AdminJPNSetRightsInfoResponse);

	/// Web service operation 'AdminJPNSearchRightsInfoList' (returns error code or SOAP_OK)
	virtual	int AdminJPNSearchRightsInfoList(_ns1__AdminJPNSearchRightsInfoList *ns1__AdminJPNSearchRightsInfoList, _ns1__AdminJPNSearchRightsInfoListResponse &ns1__AdminJPNSearchRightsInfoListResponse) { return this->AdminJPNSearchRightsInfoList(NULL, NULL, ns1__AdminJPNSearchRightsInfoList, ns1__AdminJPNSearchRightsInfoListResponse); }
	virtual	int AdminJPNSearchRightsInfoList(const char *endpoint, const char *soap_action, _ns1__AdminJPNSearchRightsInfoList *ns1__AdminJPNSearchRightsInfoList, _ns1__AdminJPNSearchRightsInfoListResponse &ns1__AdminJPNSearchRightsInfoListResponse);

	/// Web service operation 'AdminLoginRightsJPN' (returns error code or SOAP_OK)
	virtual	int AdminLoginRightsJPN(_ns1__AdminLoginRightsJPN *ns1__AdminLoginRightsJPN, _ns1__AdminLoginRightsJPNResponse &ns1__AdminLoginRightsJPNResponse) { return this->AdminLoginRightsJPN(NULL, NULL, ns1__AdminLoginRightsJPN, ns1__AdminLoginRightsJPNResponse); }
	virtual	int AdminLoginRightsJPN(const char *endpoint, const char *soap_action, _ns1__AdminLoginRightsJPN *ns1__AdminLoginRightsJPN, _ns1__AdminLoginRightsJPNResponse &ns1__AdminLoginRightsJPNResponse);

	/// Web service operation 'GetSearchLyricCount' (returns error code or SOAP_OK)
	virtual	int GetSearchLyricCount(_ns1__GetSearchLyricCount *ns1__GetSearchLyricCount, _ns1__GetSearchLyricCountResponse &ns1__GetSearchLyricCountResponse) { return this->GetSearchLyricCount(NULL, NULL, ns1__GetSearchLyricCount, ns1__GetSearchLyricCountResponse); }
	virtual	int GetSearchLyricCount(const char *endpoint, const char *soap_action, _ns1__GetSearchLyricCount *ns1__GetSearchLyricCount, _ns1__GetSearchLyricCountResponse &ns1__GetSearchLyricCountResponse);

	/// Web service operation 'AdminLoginLyricMonitor' (returns error code or SOAP_OK)
	virtual	int AdminLoginLyricMonitor(_ns1__AdminLoginLyricMonitor *ns1__AdminLoginLyricMonitor, _ns1__AdminLoginLyricMonitorResponse &ns1__AdminLoginLyricMonitorResponse) { return this->AdminLoginLyricMonitor(NULL, NULL, ns1__AdminLoginLyricMonitor, ns1__AdminLoginLyricMonitorResponse); }
	virtual	int AdminLoginLyricMonitor(const char *endpoint, const char *soap_action, _ns1__AdminLoginLyricMonitor *ns1__AdminLoginLyricMonitor, _ns1__AdminLoginLyricMonitorResponse &ns1__AdminLoginLyricMonitorResponse);

	/// Web service operation 'AdminGetLyrics' (returns error code or SOAP_OK)
	virtual	int AdminGetLyrics(_ns1__AdminGetLyrics *ns1__AdminGetLyrics, _ns1__AdminGetLyricsResponse &ns1__AdminGetLyricsResponse) { return this->AdminGetLyrics(NULL, NULL, ns1__AdminGetLyrics, ns1__AdminGetLyricsResponse); }
	virtual	int AdminGetLyrics(const char *endpoint, const char *soap_action, _ns1__AdminGetLyrics *ns1__AdminGetLyrics, _ns1__AdminGetLyricsResponse &ns1__AdminGetLyricsResponse);

	/// Web service operation 'AdminDeleteLyrics' (returns error code or SOAP_OK)
	virtual	int AdminDeleteLyrics(_ns1__AdminDeleteLyrics *ns1__AdminDeleteLyrics, _ns1__AdminDeleteLyricsResponse &ns1__AdminDeleteLyricsResponse) { return this->AdminDeleteLyrics(NULL, NULL, ns1__AdminDeleteLyrics, ns1__AdminDeleteLyricsResponse); }
	virtual	int AdminDeleteLyrics(const char *endpoint, const char *soap_action, _ns1__AdminDeleteLyrics *ns1__AdminDeleteLyrics, _ns1__AdminDeleteLyricsResponse &ns1__AdminDeleteLyricsResponse);

	/// Web service operation 'AdminGetLatestLyricID' (returns error code or SOAP_OK)
	virtual	int AdminGetLatestLyricID(_ns1__AdminGetLatestLyricID *ns1__AdminGetLatestLyricID, _ns1__AdminGetLatestLyricIDResponse &ns1__AdminGetLatestLyricIDResponse) { return this->AdminGetLatestLyricID(NULL, NULL, ns1__AdminGetLatestLyricID, ns1__AdminGetLatestLyricIDResponse); }
	virtual	int AdminGetLatestLyricID(const char *endpoint, const char *soap_action, _ns1__AdminGetLatestLyricID *ns1__AdminGetLatestLyricID, _ns1__AdminGetLatestLyricIDResponse &ns1__AdminGetLatestLyricIDResponse);

	/// Web service operation 'GetMurekaInfo' (returns error code or SOAP_OK)
	virtual	int GetMurekaInfo_(_ns1__GetMurekaInfo *ns1__GetMurekaInfo, _ns1__GetMurekaInfoResponse &ns1__GetMurekaInfoResponse) { return this->GetMurekaInfo_(NULL, NULL, ns1__GetMurekaInfo, ns1__GetMurekaInfoResponse); }
	virtual	int GetMurekaInfo_(const char *endpoint, const char *soap_action, _ns1__GetMurekaInfo *ns1__GetMurekaInfo, _ns1__GetMurekaInfoResponse &ns1__GetMurekaInfoResponse);

	/// Web service operation 'GetSyncLyricBySearch' (returns error code or SOAP_OK)
	virtual	int GetSyncLyricBySearch_(_ns1__GetSyncLyricBySearch *ns1__GetSyncLyricBySearch, _ns1__GetSyncLyricBySearchResponse &ns1__GetSyncLyricBySearchResponse) { return this->GetSyncLyricBySearch_(NULL, NULL, ns1__GetSyncLyricBySearch, ns1__GetSyncLyricBySearchResponse); }
	virtual	int GetSyncLyricBySearch_(const char *endpoint, const char *soap_action, _ns1__GetSyncLyricBySearch *ns1__GetSyncLyricBySearch, _ns1__GetSyncLyricBySearchResponse &ns1__GetSyncLyricBySearchResponse);

	/// Web service operation 'SetLinkLyric' (returns error code or SOAP_OK)
	virtual	int SetLinkLyric_(_ns1__SetLinkLyric *ns1__SetLinkLyric, _ns1__SetLinkLyricResponse &ns1__SetLinkLyricResponse) { return this->SetLinkLyric_(NULL, NULL, ns1__SetLinkLyric, ns1__SetLinkLyricResponse); }
	virtual	int SetLinkLyric_(const char *endpoint, const char *soap_action, _ns1__SetLinkLyric *ns1__SetLinkLyric, _ns1__SetLinkLyricResponse &ns1__SetLinkLyricResponse);

	/// Web service operation 'GetResembleLyric2' (returns error code or SOAP_OK)
	virtual	int GetResembleLyric2_(_ns1__GetResembleLyric2 *ns1__GetResembleLyric2, _ns1__GetResembleLyric2Response &ns1__GetResembleLyric2Response) { return this->GetResembleLyric2_(NULL, NULL, ns1__GetResembleLyric2, ns1__GetResembleLyric2Response); }
	virtual	int GetResembleLyric2_(const char *endpoint, const char *soap_action, _ns1__GetResembleLyric2 *ns1__GetResembleLyric2, _ns1__GetResembleLyric2Response &ns1__GetResembleLyric2Response);

	/// Web service operation 'GetResembleLyric3' (returns error code or SOAP_OK)
	virtual	int GetResembleLyric3_(_ns1__GetResembleLyric3 *ns1__GetResembleLyric3, _ns1__GetResembleLyric3Response &ns1__GetResembleLyric3Response) { return this->GetResembleLyric3_(NULL, NULL, ns1__GetResembleLyric3, ns1__GetResembleLyric3Response); }
	virtual	int GetResembleLyric3_(const char *endpoint, const char *soap_action, _ns1__GetResembleLyric3 *ns1__GetResembleLyric3, _ns1__GetResembleLyric3Response &ns1__GetResembleLyric3Response);

	/// Web service operation 'GetResembleLyric2Count' (returns error code or SOAP_OK)
	virtual	int GetResembleLyric2Count_(_ns1__GetResembleLyric2Count *ns1__GetResembleLyric2Count, _ns1__GetResembleLyric2CountResponse &ns1__GetResembleLyric2CountResponse) { return this->GetResembleLyric2Count_(NULL, NULL, ns1__GetResembleLyric2Count, ns1__GetResembleLyric2CountResponse); }
	virtual	int GetResembleLyric2Count_(const char *endpoint, const char *soap_action, _ns1__GetResembleLyric2Count *ns1__GetResembleLyric2Count, _ns1__GetResembleLyric2CountResponse &ns1__GetResembleLyric2CountResponse);

	/// Web service operation 'GetResembleLyric2CountTest' (returns error code or SOAP_OK)
	virtual	int GetResembleLyric2CountTest_(_ns1__GetResembleLyric2CountTest *ns1__GetResembleLyric2CountTest, _ns1__GetResembleLyric2CountTestResponse &ns1__GetResembleLyric2CountTestResponse) { return this->GetResembleLyric2CountTest_(NULL, NULL, ns1__GetResembleLyric2CountTest, ns1__GetResembleLyric2CountTestResponse); }
	virtual	int GetResembleLyric2CountTest_(const char *endpoint, const char *soap_action, _ns1__GetResembleLyric2CountTest *ns1__GetResembleLyric2CountTest, _ns1__GetResembleLyric2CountTestResponse &ns1__GetResembleLyric2CountTestResponse);

	/// Web service operation 'UploadLyric' (returns error code or SOAP_OK)
	virtual	int UploadLyric_(_ns1__UploadLyric *ns1__UploadLyric, _ns1__UploadLyricResponse &ns1__UploadLyricResponse) { return this->UploadLyric_(NULL, NULL, ns1__UploadLyric, ns1__UploadLyricResponse); }
	virtual	int UploadLyric_(const char *endpoint, const char *soap_action, _ns1__UploadLyric *ns1__UploadLyric, _ns1__UploadLyricResponse &ns1__UploadLyricResponse);

	/// Web service operation 'ReportFaultLyricWithComment' (returns error code or SOAP_OK)
	virtual	int ReportFaultLyricWithComment_(_ns1__ReportFaultLyricWithComment *ns1__ReportFaultLyricWithComment, _ns1__ReportFaultLyricWithCommentResponse &ns1__ReportFaultLyricWithCommentResponse) { return this->ReportFaultLyricWithComment_(NULL, NULL, ns1__ReportFaultLyricWithComment, ns1__ReportFaultLyricWithCommentResponse); }
	virtual	int ReportFaultLyricWithComment_(const char *endpoint, const char *soap_action, _ns1__ReportFaultLyricWithComment *ns1__ReportFaultLyricWithComment, _ns1__ReportFaultLyricWithCommentResponse &ns1__ReportFaultLyricWithCommentResponse);

	/// Web service operation 'ReportFaultLyric2' (returns error code or SOAP_OK)
	virtual	int ReportFaultLyric2_(_ns1__ReportFaultLyric2 *ns1__ReportFaultLyric2, _ns1__ReportFaultLyric2Response &ns1__ReportFaultLyric2Response) { return this->ReportFaultLyric2_(NULL, NULL, ns1__ReportFaultLyric2, ns1__ReportFaultLyric2Response); }
	virtual	int ReportFaultLyric2_(const char *endpoint, const char *soap_action, _ns1__ReportFaultLyric2 *ns1__ReportFaultLyric2, _ns1__ReportFaultLyric2Response &ns1__ReportFaultLyric2Response);

	/// Web service operation 'ReportRecommendationLyric' (returns error code or SOAP_OK)
	virtual	int ReportRecommendationLyric_(_ns1__ReportRecommendationLyric *ns1__ReportRecommendationLyric, _ns1__ReportRecommendationLyricResponse &ns1__ReportRecommendationLyricResponse) { return this->ReportRecommendationLyric_(NULL, NULL, ns1__ReportRecommendationLyric, ns1__ReportRecommendationLyricResponse); }
	virtual	int ReportRecommendationLyric_(const char *endpoint, const char *soap_action, _ns1__ReportRecommendationLyric *ns1__ReportRecommendationLyric, _ns1__ReportRecommendationLyricResponse &ns1__ReportRecommendationLyricResponse);

	/// Web service operation 'IsReportedRecommendationLyric' (returns error code or SOAP_OK)
	virtual	int IsReportedRecommendationLyric_(_ns1__IsReportedRecommendationLyric *ns1__IsReportedRecommendationLyric, _ns1__IsReportedRecommendationLyricResponse &ns1__IsReportedRecommendationLyricResponse) { return this->IsReportedRecommendationLyric_(NULL, NULL, ns1__IsReportedRecommendationLyric, ns1__IsReportedRecommendationLyricResponse); }
	virtual	int IsReportedRecommendationLyric_(const char *endpoint, const char *soap_action, _ns1__IsReportedRecommendationLyric *ns1__IsReportedRecommendationLyric, _ns1__IsReportedRecommendationLyricResponse &ns1__IsReportedRecommendationLyricResponse);

	/// Web service operation 'IsReportedFaultLyric' (returns error code or SOAP_OK)
	virtual	int IsReportedFaultLyric_(_ns1__IsReportedFaultLyric *ns1__IsReportedFaultLyric, _ns1__IsReportedFaultLyricResponse &ns1__IsReportedFaultLyricResponse) { return this->IsReportedFaultLyric_(NULL, NULL, ns1__IsReportedFaultLyric, ns1__IsReportedFaultLyricResponse); }
	virtual	int IsReportedFaultLyric_(const char *endpoint, const char *soap_action, _ns1__IsReportedFaultLyric *ns1__IsReportedFaultLyric, _ns1__IsReportedFaultLyricResponse &ns1__IsReportedFaultLyricResponse);

	/// Web service operation 'GetLyric3' (returns error code or SOAP_OK)
	virtual	int GetLyric3_(_ns1__GetLyric3 *ns1__GetLyric3, _ns1__GetLyric3Response &ns1__GetLyric3Response) { return this->GetLyric3_(NULL, NULL, ns1__GetLyric3, ns1__GetLyric3Response); }
	virtual	int GetLyric3_(const char *endpoint, const char *soap_action, _ns1__GetLyric3 *ns1__GetLyric3, _ns1__GetLyric3Response &ns1__GetLyric3Response);

	/// Web service operation 'GetLyric4' (returns error code or SOAP_OK)
	virtual	int GetLyric4_(_ns1__GetLyric4 *ns1__GetLyric4, _ns1__GetLyric4Response &ns1__GetLyric4Response) { return this->GetLyric4_(NULL, NULL, ns1__GetLyric4, ns1__GetLyric4Response); }
	virtual	int GetLyric4_(const char *endpoint, const char *soap_action, _ns1__GetLyric4 *ns1__GetLyric4, _ns1__GetLyric4Response &ns1__GetLyric4Response);

	/// Web service operation 'GetLyric5' (returns error code or SOAP_OK)
	virtual	int GetLyric5_(_ns1__GetLyric5 *ns1__GetLyric5, _ns1__GetLyric5Response &ns1__GetLyric5Response) { return this->GetLyric5_(NULL, NULL, ns1__GetLyric5, ns1__GetLyric5Response); }
	virtual	int GetLyric5_(const char *endpoint, const char *soap_action, _ns1__GetLyric5 *ns1__GetLyric5, _ns1__GetLyric5Response &ns1__GetLyric5Response);

	/// Web service operation 'GetLyric6' (returns error code or SOAP_OK)
	virtual	int GetLyric6_(_ns1__GetLyric6 *ns1__GetLyric6, _ns1__GetLyric6Response &ns1__GetLyric6Response) { return this->GetLyric6_(NULL, NULL, ns1__GetLyric6, ns1__GetLyric6Response); }
	virtual	int GetLyric6_(const char *endpoint, const char *soap_action, _ns1__GetLyric6 *ns1__GetLyric6, _ns1__GetLyric6Response &ns1__GetLyric6Response);

	/// Web service operation 'GetLyric7' (returns error code or SOAP_OK)
	virtual	int GetLyric7_(_ns1__GetLyric7 *ns1__GetLyric7, _ns1__GetLyric7Response &ns1__GetLyric7Response) { return this->GetLyric7_(NULL, NULL, ns1__GetLyric7, ns1__GetLyric7Response); }
	virtual	int GetLyric7_(const char *endpoint, const char *soap_action, _ns1__GetLyric7 *ns1__GetLyric7, _ns1__GetLyric7Response &ns1__GetLyric7Response);

	/// Web service operation 'GetLyric8' (returns error code or SOAP_OK)
	virtual	int GetLyric8_(_ns1__GetLyric8 *ns1__GetLyric8, _ns1__GetLyric8Response &ns1__GetLyric8Response) { return this->GetLyric8_(NULL, NULL, ns1__GetLyric8, ns1__GetLyric8Response); }
	virtual	int GetLyric8_(const char *endpoint, const char *soap_action, _ns1__GetLyric8 *ns1__GetLyric8, _ns1__GetLyric8Response &ns1__GetLyric8Response);

	/// Web service operation 'GetSongID' (returns error code or SOAP_OK)
	virtual	int GetSongID_(_ns1__GetSongID *ns1__GetSongID, _ns1__GetSongIDResponse &ns1__GetSongIDResponse) { return this->GetSongID_(NULL, NULL, ns1__GetSongID, ns1__GetSongIDResponse); }
	virtual	int GetSongID_(const char *endpoint, const char *soap_action, _ns1__GetSongID *ns1__GetSongID, _ns1__GetSongIDResponse &ns1__GetSongIDResponse);

	/// Web service operation 'AdminGetLyricList' (returns error code or SOAP_OK)
	virtual	int AdminGetLyricList_(_ns1__AdminGetLyricList *ns1__AdminGetLyricList, _ns1__AdminGetLyricListResponse &ns1__AdminGetLyricListResponse) { return this->AdminGetLyricList_(NULL, NULL, ns1__AdminGetLyricList, ns1__AdminGetLyricListResponse); }
	virtual	int AdminGetLyricList_(const char *endpoint, const char *soap_action, _ns1__AdminGetLyricList *ns1__AdminGetLyricList, _ns1__AdminGetLyricListResponse &ns1__AdminGetLyricListResponse);

	/// Web service operation 'AdminGetLyricListByID' (returns error code or SOAP_OK)
	virtual	int AdminGetLyricListByID_(_ns1__AdminGetLyricListByID *ns1__AdminGetLyricListByID, _ns1__AdminGetLyricListByIDResponse &ns1__AdminGetLyricListByIDResponse) { return this->AdminGetLyricListByID_(NULL, NULL, ns1__AdminGetLyricListByID, ns1__AdminGetLyricListByIDResponse); }
	virtual	int AdminGetLyricListByID_(const char *endpoint, const char *soap_action, _ns1__AdminGetLyricListByID *ns1__AdminGetLyricListByID, _ns1__AdminGetLyricListByIDResponse &ns1__AdminGetLyricListByIDResponse);

	/// Web service operation 'AdminGetReportFaultList' (returns error code or SOAP_OK)
	virtual	int AdminGetReportFaultList_(_ns1__AdminGetReportFaultList *ns1__AdminGetReportFaultList, _ns1__AdminGetReportFaultListResponse &ns1__AdminGetReportFaultListResponse) { return this->AdminGetReportFaultList_(NULL, NULL, ns1__AdminGetReportFaultList, ns1__AdminGetReportFaultListResponse); }
	virtual	int AdminGetReportFaultList_(const char *endpoint, const char *soap_action, _ns1__AdminGetReportFaultList *ns1__AdminGetReportFaultList, _ns1__AdminGetReportFaultListResponse &ns1__AdminGetReportFaultListResponse);

	/// Web service operation 'AdminGetModifyList' (returns error code or SOAP_OK)
	virtual	int AdminGetModifyList_(_ns1__AdminGetModifyList *ns1__AdminGetModifyList, _ns1__AdminGetModifyListResponse &ns1__AdminGetModifyListResponse) { return this->AdminGetModifyList_(NULL, NULL, ns1__AdminGetModifyList, ns1__AdminGetModifyListResponse); }
	virtual	int AdminGetModifyList_(const char *endpoint, const char *soap_action, _ns1__AdminGetModifyList *ns1__AdminGetModifyList, _ns1__AdminGetModifyListResponse &ns1__AdminGetModifyListResponse);

	/// Web service operation 'AdminGetRegisterList' (returns error code or SOAP_OK)
	virtual	int AdminGetRegisterList_(_ns1__AdminGetRegisterList *ns1__AdminGetRegisterList, _ns1__AdminGetRegisterListResponse &ns1__AdminGetRegisterListResponse) { return this->AdminGetRegisterList_(NULL, NULL, ns1__AdminGetRegisterList, ns1__AdminGetRegisterListResponse); }
	virtual	int AdminGetRegisterList_(const char *endpoint, const char *soap_action, _ns1__AdminGetRegisterList *ns1__AdminGetRegisterList, _ns1__AdminGetRegisterListResponse &ns1__AdminGetRegisterListResponse);

	/// Web service operation 'MemberAddMember' (returns error code or SOAP_OK)
	virtual	int MemberAddMember_(_ns1__MemberAddMember *ns1__MemberAddMember, _ns1__MemberAddMemberResponse &ns1__MemberAddMemberResponse) { return this->MemberAddMember_(NULL, NULL, ns1__MemberAddMember, ns1__MemberAddMemberResponse); }
	virtual	int MemberAddMember_(const char *endpoint, const char *soap_action, _ns1__MemberAddMember *ns1__MemberAddMember, _ns1__MemberAddMemberResponse &ns1__MemberAddMemberResponse);

	/// Web service operation 'MemberModifyMember' (returns error code or SOAP_OK)
	virtual	int MemberModifyMember_(_ns1__MemberModifyMember *ns1__MemberModifyMember, _ns1__MemberModifyMemberResponse &ns1__MemberModifyMemberResponse) { return this->MemberModifyMember_(NULL, NULL, ns1__MemberModifyMember, ns1__MemberModifyMemberResponse); }
	virtual	int MemberModifyMember_(const char *endpoint, const char *soap_action, _ns1__MemberModifyMember *ns1__MemberModifyMember, _ns1__MemberModifyMemberResponse &ns1__MemberModifyMemberResponse);

	/// Web service operation 'MemberRemoveMember' (returns error code or SOAP_OK)
	virtual	int MemberRemoveMember_(_ns1__MemberRemoveMember *ns1__MemberRemoveMember, _ns1__MemberRemoveMemberResponse &ns1__MemberRemoveMemberResponse) { return this->MemberRemoveMember_(NULL, NULL, ns1__MemberRemoveMember, ns1__MemberRemoveMemberResponse); }
	virtual	int MemberRemoveMember_(const char *endpoint, const char *soap_action, _ns1__MemberRemoveMember *ns1__MemberRemoveMember, _ns1__MemberRemoveMemberResponse &ns1__MemberRemoveMemberResponse);

	/// Web service operation 'MemberLogin' (returns error code or SOAP_OK)
	virtual	int MemberLogin_(_ns1__MemberLogin *ns1__MemberLogin, _ns1__MemberLoginResponse &ns1__MemberLoginResponse) { return this->MemberLogin_(NULL, NULL, ns1__MemberLogin, ns1__MemberLoginResponse); }
	virtual	int MemberLogin_(const char *endpoint, const char *soap_action, _ns1__MemberLogin *ns1__MemberLogin, _ns1__MemberLoginResponse &ns1__MemberLoginResponse);

	/// Web service operation 'MemberLogout' (returns error code or SOAP_OK)
	virtual	int MemberLogout_(_ns1__MemberLogout *ns1__MemberLogout, _ns1__MemberLogoutResponse &ns1__MemberLogoutResponse) { return this->MemberLogout_(NULL, NULL, ns1__MemberLogout, ns1__MemberLogoutResponse); }
	virtual	int MemberLogout_(const char *endpoint, const char *soap_action, _ns1__MemberLogout *ns1__MemberLogout, _ns1__MemberLogoutResponse &ns1__MemberLogoutResponse);

	/// Web service operation 'MemberApplyRegistration' (returns error code or SOAP_OK)
	virtual	int MemberApplyRegistration_(_ns1__MemberApplyRegistration *ns1__MemberApplyRegistration, _ns1__MemberApplyRegistrationResponse &ns1__MemberApplyRegistrationResponse) { return this->MemberApplyRegistration_(NULL, NULL, ns1__MemberApplyRegistration, ns1__MemberApplyRegistrationResponse); }
	virtual	int MemberApplyRegistration_(const char *endpoint, const char *soap_action, _ns1__MemberApplyRegistration *ns1__MemberApplyRegistration, _ns1__MemberApplyRegistrationResponse &ns1__MemberApplyRegistrationResponse);

	/// Web service operation 'MemberModifyMemberLicense' (returns error code or SOAP_OK)
	virtual	int MemberModifyMemberLicense_(_ns1__MemberModifyMemberLicense *ns1__MemberModifyMemberLicense, _ns1__MemberModifyMemberLicenseResponse &ns1__MemberModifyMemberLicenseResponse) { return this->MemberModifyMemberLicense_(NULL, NULL, ns1__MemberModifyMemberLicense, ns1__MemberModifyMemberLicenseResponse); }
	virtual	int MemberModifyMemberLicense_(const char *endpoint, const char *soap_action, _ns1__MemberModifyMemberLicense *ns1__MemberModifyMemberLicense, _ns1__MemberModifyMemberLicenseResponse &ns1__MemberModifyMemberLicenseResponse);

	/// Web service operation 'MemberGetMemberList' (returns error code or SOAP_OK)
	virtual	int MemberGetMemberList_(_ns1__MemberGetMemberList *ns1__MemberGetMemberList, _ns1__MemberGetMemberListResponse &ns1__MemberGetMemberListResponse) { return this->MemberGetMemberList_(NULL, NULL, ns1__MemberGetMemberList, ns1__MemberGetMemberListResponse); }
	virtual	int MemberGetMemberList_(const char *endpoint, const char *soap_action, _ns1__MemberGetMemberList *ns1__MemberGetMemberList, _ns1__MemberGetMemberListResponse &ns1__MemberGetMemberListResponse);

	/// Web service operation 'MemberGetMemberLicenseList' (returns error code or SOAP_OK)
	virtual	int MemberGetMemberLicenseList_(_ns1__MemberGetMemberLicenseList *ns1__MemberGetMemberLicenseList, _ns1__MemberGetMemberLicenseListResponse &ns1__MemberGetMemberLicenseListResponse) { return this->MemberGetMemberLicenseList_(NULL, NULL, ns1__MemberGetMemberLicenseList, ns1__MemberGetMemberLicenseListResponse); }
	virtual	int MemberGetMemberLicenseList_(const char *endpoint, const char *soap_action, _ns1__MemberGetMemberLicenseList *ns1__MemberGetMemberLicenseList, _ns1__MemberGetMemberLicenseListResponse &ns1__MemberGetMemberLicenseListResponse);

	/// Web service operation 'AdminDeleteRecord' (returns error code or SOAP_OK)
	virtual	int AdminDeleteRecord_(_ns1__AdminDeleteRecord *ns1__AdminDeleteRecord, _ns1__AdminDeleteRecordResponse &ns1__AdminDeleteRecordResponse) { return this->AdminDeleteRecord_(NULL, NULL, ns1__AdminDeleteRecord, ns1__AdminDeleteRecordResponse); }
	virtual	int AdminDeleteRecord_(const char *endpoint, const char *soap_action, _ns1__AdminDeleteRecord *ns1__AdminDeleteRecord, _ns1__AdminDeleteRecordResponse &ns1__AdminDeleteRecordResponse);

	/// Web service operation 'AdminAdmitModifyLyric' (returns error code or SOAP_OK)
	virtual	int AdminAdmitModifyLyric_(_ns1__AdminAdmitModifyLyric *ns1__AdminAdmitModifyLyric, _ns1__AdminAdmitModifyLyricResponse &ns1__AdminAdmitModifyLyricResponse) { return this->AdminAdmitModifyLyric_(NULL, NULL, ns1__AdminAdmitModifyLyric, ns1__AdminAdmitModifyLyricResponse); }
	virtual	int AdminAdmitModifyLyric_(const char *endpoint, const char *soap_action, _ns1__AdminAdmitModifyLyric *ns1__AdminAdmitModifyLyric, _ns1__AdminAdmitModifyLyricResponse &ns1__AdminAdmitModifyLyricResponse);

	/// Web service operation 'AdminReportBlackList' (returns error code or SOAP_OK)
	virtual	int AdminReportBlackList_(_ns1__AdminReportBlackList *ns1__AdminReportBlackList, _ns1__AdminReportBlackListResponse &ns1__AdminReportBlackListResponse) { return this->AdminReportBlackList_(NULL, NULL, ns1__AdminReportBlackList, ns1__AdminReportBlackListResponse); }
	virtual	int AdminReportBlackList_(const char *endpoint, const char *soap_action, _ns1__AdminReportBlackList *ns1__AdminReportBlackList, _ns1__AdminReportBlackListResponse &ns1__AdminReportBlackListResponse);

	/// Web service operation 'AdminGetCountInRegister' (returns error code or SOAP_OK)
	virtual	int AdminGetCountInRegister_(_ns1__AdminGetCountInRegister *ns1__AdminGetCountInRegister, _ns1__AdminGetCountInRegisterResponse &ns1__AdminGetCountInRegisterResponse) { return this->AdminGetCountInRegister_(NULL, NULL, ns1__AdminGetCountInRegister, ns1__AdminGetCountInRegisterResponse); }
	virtual	int AdminGetCountInRegister_(const char *endpoint, const char *soap_action, _ns1__AdminGetCountInRegister *ns1__AdminGetCountInRegister, _ns1__AdminGetCountInRegisterResponse &ns1__AdminGetCountInRegisterResponse);

	/// Web service operation 'AdminGetCountChecksum' (returns error code or SOAP_OK)
	virtual	int AdminGetCountChecksum_(_ns1__AdminGetCountChecksum *ns1__AdminGetCountChecksum, _ns1__AdminGetCountChecksumResponse &ns1__AdminGetCountChecksumResponse) { return this->AdminGetCountChecksum_(NULL, NULL, ns1__AdminGetCountChecksum, ns1__AdminGetCountChecksumResponse); }
	virtual	int AdminGetCountChecksum_(const char *endpoint, const char *soap_action, _ns1__AdminGetCountChecksum *ns1__AdminGetCountChecksum, _ns1__AdminGetCountChecksumResponse &ns1__AdminGetCountChecksumResponse);

	/// Web service operation 'AdminGetCountLyric' (returns error code or SOAP_OK)
	virtual	int AdminGetCountLyric_(_ns1__AdminGetCountLyric *ns1__AdminGetCountLyric, _ns1__AdminGetCountLyricResponse &ns1__AdminGetCountLyricResponse) { return this->AdminGetCountLyric_(NULL, NULL, ns1__AdminGetCountLyric, ns1__AdminGetCountLyricResponse); }
	virtual	int AdminGetCountLyric_(const char *endpoint, const char *soap_action, _ns1__AdminGetCountLyric *ns1__AdminGetCountLyric, _ns1__AdminGetCountLyricResponse &ns1__AdminGetCountLyricResponse);

	/// Web service operation 'AdminGetCountModify' (returns error code or SOAP_OK)
	virtual	int AdminGetCountModify_(_ns1__AdminGetCountModify *ns1__AdminGetCountModify, _ns1__AdminGetCountModifyResponse &ns1__AdminGetCountModifyResponse) { return this->AdminGetCountModify_(NULL, NULL, ns1__AdminGetCountModify, ns1__AdminGetCountModifyResponse); }
	virtual	int AdminGetCountModify_(const char *endpoint, const char *soap_action, _ns1__AdminGetCountModify *ns1__AdminGetCountModify, _ns1__AdminGetCountModifyResponse &ns1__AdminGetCountModifyResponse);

	/// Web service operation 'AdminGetCountReport' (returns error code or SOAP_OK)
	virtual	int AdminGetCountReport_(_ns1__AdminGetCountReport *ns1__AdminGetCountReport, _ns1__AdminGetCountReportResponse &ns1__AdminGetCountReportResponse) { return this->AdminGetCountReport_(NULL, NULL, ns1__AdminGetCountReport, ns1__AdminGetCountReportResponse); }
	virtual	int AdminGetCountReport_(const char *endpoint, const char *soap_action, _ns1__AdminGetCountReport *ns1__AdminGetCountReport, _ns1__AdminGetCountReportResponse &ns1__AdminGetCountReportResponse);

	/// Web service operation 'AdminGetAlbaStatistic' (returns error code or SOAP_OK)
	virtual	int AdminGetAlbaStatistic_(_ns1__AdminGetAlbaStatistic *ns1__AdminGetAlbaStatistic, _ns1__AdminGetAlbaStatisticResponse &ns1__AdminGetAlbaStatisticResponse) { return this->AdminGetAlbaStatistic_(NULL, NULL, ns1__AdminGetAlbaStatistic, ns1__AdminGetAlbaStatisticResponse); }
	virtual	int AdminGetAlbaStatistic_(const char *endpoint, const char *soap_action, _ns1__AdminGetAlbaStatistic *ns1__AdminGetAlbaStatistic, _ns1__AdminGetAlbaStatisticResponse &ns1__AdminGetAlbaStatisticResponse);

	/// Web service operation 'CastUploadExMetaData' (returns error code or SOAP_OK)
	virtual	int CastUploadExMetaData_(_ns1__CastUploadExMetaData *ns1__CastUploadExMetaData, _ns1__CastUploadExMetaDataResponse &ns1__CastUploadExMetaDataResponse) { return this->CastUploadExMetaData_(NULL, NULL, ns1__CastUploadExMetaData, ns1__CastUploadExMetaDataResponse); }
	virtual	int CastUploadExMetaData_(const char *endpoint, const char *soap_action, _ns1__CastUploadExMetaData *ns1__CastUploadExMetaData, _ns1__CastUploadExMetaDataResponse &ns1__CastUploadExMetaDataResponse);

	/// Web service operation 'CastUploadExMetaData2' (returns error code or SOAP_OK)
	virtual	int CastUploadExMetaData2_(_ns1__CastUploadExMetaData2 *ns1__CastUploadExMetaData2, _ns1__CastUploadExMetaData2Response &ns1__CastUploadExMetaData2Response) { return this->CastUploadExMetaData2_(NULL, NULL, ns1__CastUploadExMetaData2, ns1__CastUploadExMetaData2Response); }
	virtual	int CastUploadExMetaData2_(const char *endpoint, const char *soap_action, _ns1__CastUploadExMetaData2 *ns1__CastUploadExMetaData2, _ns1__CastUploadExMetaData2Response &ns1__CastUploadExMetaData2Response);

	/// Web service operation 'CastUploadExMetaData3' (returns error code or SOAP_OK)
	virtual	int CastUploadExMetaData3_(_ns1__CastUploadExMetaData3 *ns1__CastUploadExMetaData3, _ns1__CastUploadExMetaData3Response &ns1__CastUploadExMetaData3Response) { return this->CastUploadExMetaData3_(NULL, NULL, ns1__CastUploadExMetaData3, ns1__CastUploadExMetaData3Response); }
	virtual	int CastUploadExMetaData3_(const char *endpoint, const char *soap_action, _ns1__CastUploadExMetaData3 *ns1__CastUploadExMetaData3, _ns1__CastUploadExMetaData3Response &ns1__CastUploadExMetaData3Response);

	/// Web service operation 'CastRemoveExMetaData' (returns error code or SOAP_OK)
	virtual	int CastRemoveExMetaData_(_ns1__CastRemoveExMetaData *ns1__CastRemoveExMetaData, _ns1__CastRemoveExMetaDataResponse &ns1__CastRemoveExMetaDataResponse) { return this->CastRemoveExMetaData_(NULL, NULL, ns1__CastRemoveExMetaData, ns1__CastRemoveExMetaDataResponse); }
	virtual	int CastRemoveExMetaData_(const char *endpoint, const char *soap_action, _ns1__CastRemoveExMetaData *ns1__CastRemoveExMetaData, _ns1__CastRemoveExMetaDataResponse &ns1__CastRemoveExMetaDataResponse);

	/// Web service operation 'CastGetExMetaData' (returns error code or SOAP_OK)
	virtual	int CastGetExMetaData_(_ns1__CastGetExMetaData *ns1__CastGetExMetaData, _ns1__CastGetExMetaDataResponse &ns1__CastGetExMetaDataResponse) { return this->CastGetExMetaData_(NULL, NULL, ns1__CastGetExMetaData, ns1__CastGetExMetaDataResponse); }
	virtual	int CastGetExMetaData_(const char *endpoint, const char *soap_action, _ns1__CastGetExMetaData *ns1__CastGetExMetaData, _ns1__CastGetExMetaDataResponse &ns1__CastGetExMetaDataResponse);

	/// Web service operation 'CastGetExMetaDataList' (returns error code or SOAP_OK)
	virtual	int CastGetExMetaDataList_(_ns1__CastGetExMetaDataList *ns1__CastGetExMetaDataList, _ns1__CastGetExMetaDataListResponse &ns1__CastGetExMetaDataListResponse) { return this->CastGetExMetaDataList_(NULL, NULL, ns1__CastGetExMetaDataList, ns1__CastGetExMetaDataListResponse); }
	virtual	int CastGetExMetaDataList_(const char *endpoint, const char *soap_action, _ns1__CastGetExMetaDataList *ns1__CastGetExMetaDataList, _ns1__CastGetExMetaDataListResponse &ns1__CastGetExMetaDataListResponse);

	/// Web service operation 'CastGetExMetaDataList2' (returns error code or SOAP_OK)
	virtual	int CastGetExMetaDataList2_(_ns1__CastGetExMetaDataList2 *ns1__CastGetExMetaDataList2, _ns1__CastGetExMetaDataList2Response &ns1__CastGetExMetaDataList2Response) { return this->CastGetExMetaDataList2_(NULL, NULL, ns1__CastGetExMetaDataList2, ns1__CastGetExMetaDataList2Response); }
	virtual	int CastGetExMetaDataList2_(const char *endpoint, const char *soap_action, _ns1__CastGetExMetaDataList2 *ns1__CastGetExMetaDataList2, _ns1__CastGetExMetaDataList2Response &ns1__CastGetExMetaDataList2Response);

	/// Web service operation 'CastGetExMetaDataList3' (returns error code or SOAP_OK)
	virtual	int CastGetExMetaDataList3_(_ns1__CastGetExMetaDataList3 *ns1__CastGetExMetaDataList3, _ns1__CastGetExMetaDataList3Response &ns1__CastGetExMetaDataList3Response) { return this->CastGetExMetaDataList3_(NULL, NULL, ns1__CastGetExMetaDataList3, ns1__CastGetExMetaDataList3Response); }
	virtual	int CastGetExMetaDataList3_(const char *endpoint, const char *soap_action, _ns1__CastGetExMetaDataList3 *ns1__CastGetExMetaDataList3, _ns1__CastGetExMetaDataList3Response &ns1__CastGetExMetaDataList3Response);

	/// Web service operation 'GetBroadcastingList' (returns error code or SOAP_OK)
	virtual	int GetBroadcastingList_(_ns1__GetBroadcastingList *ns1__GetBroadcastingList, _ns1__GetBroadcastingListResponse &ns1__GetBroadcastingListResponse) { return this->GetBroadcastingList_(NULL, NULL, ns1__GetBroadcastingList, ns1__GetBroadcastingListResponse); }
	virtual	int GetBroadcastingList_(const char *endpoint, const char *soap_action, _ns1__GetBroadcastingList *ns1__GetBroadcastingList, _ns1__GetBroadcastingListResponse &ns1__GetBroadcastingListResponse);

	/// Web service operation 'GetBroadcastingList2' (returns error code or SOAP_OK)
	virtual	int GetBroadcastingList2_(_ns1__GetBroadcastingList2 *ns1__GetBroadcastingList2, _ns1__GetBroadcastingList2Response &ns1__GetBroadcastingList2Response) { return this->GetBroadcastingList2_(NULL, NULL, ns1__GetBroadcastingList2, ns1__GetBroadcastingList2Response); }
	virtual	int GetBroadcastingList2_(const char *endpoint, const char *soap_action, _ns1__GetBroadcastingList2 *ns1__GetBroadcastingList2, _ns1__GetBroadcastingList2Response &ns1__GetBroadcastingList2Response);

	/// Web service operation 'UploadForeignLyric' (returns error code or SOAP_OK)
	virtual	int UploadForeignLyric_(_ns1__UploadForeignLyric *ns1__UploadForeignLyric, _ns1__UploadForeignLyricResponse &ns1__UploadForeignLyricResponse) { return this->UploadForeignLyric_(NULL, NULL, ns1__UploadForeignLyric, ns1__UploadForeignLyricResponse); }
	virtual	int UploadForeignLyric_(const char *endpoint, const char *soap_action, _ns1__UploadForeignLyric *ns1__UploadForeignLyric, _ns1__UploadForeignLyricResponse &ns1__UploadForeignLyricResponse);

	/// Web service operation 'GetResembleLyricList' (returns error code or SOAP_OK)
	virtual	int GetResembleLyricList_(_ns1__GetResembleLyricList *ns1__GetResembleLyricList, _ns1__GetResembleLyricListResponse &ns1__GetResembleLyricListResponse) { return this->GetResembleLyricList_(NULL, NULL, ns1__GetResembleLyricList, ns1__GetResembleLyricListResponse); }
	virtual	int GetResembleLyricList_(const char *endpoint, const char *soap_action, _ns1__GetResembleLyricList *ns1__GetResembleLyricList, _ns1__GetResembleLyricListResponse &ns1__GetResembleLyricListResponse);

	/// Web service operation 'GetResembleLyricList2' (returns error code or SOAP_OK)
	virtual	int GetResembleLyricList2_(_ns1__GetResembleLyricList2 *ns1__GetResembleLyricList2, _ns1__GetResembleLyricList2Response &ns1__GetResembleLyricList2Response) { return this->GetResembleLyricList2_(NULL, NULL, ns1__GetResembleLyricList2, ns1__GetResembleLyricList2Response); }
	virtual	int GetResembleLyricList2_(const char *endpoint, const char *soap_action, _ns1__GetResembleLyricList2 *ns1__GetResembleLyricList2, _ns1__GetResembleLyricList2Response &ns1__GetResembleLyricList2Response);

	/// Web service operation 'GetLyricByID' (returns error code or SOAP_OK)
	virtual	int GetLyricByID_(_ns1__GetLyricByID *ns1__GetLyricByID, _ns1__GetLyricByIDResponse &ns1__GetLyricByIDResponse) { return this->GetLyricByID_(NULL, NULL, ns1__GetLyricByID, ns1__GetLyricByIDResponse); }
	virtual	int GetLyricByID_(const char *endpoint, const char *soap_action, _ns1__GetLyricByID *ns1__GetLyricByID, _ns1__GetLyricByIDResponse &ns1__GetLyricByIDResponse);

	/// Web service operation 'GetLyricByID2' (returns error code or SOAP_OK)
	virtual	int GetLyricByID2_(_ns1__GetLyricByID2 *ns1__GetLyricByID2, _ns1__GetLyricByID2Response &ns1__GetLyricByID2Response) { return this->GetLyricByID2_(NULL, NULL, ns1__GetLyricByID2, ns1__GetLyricByID2Response); }
	virtual	int GetLyricByID2_(const char *endpoint, const char *soap_action, _ns1__GetLyricByID2 *ns1__GetLyricByID2, _ns1__GetLyricByID2Response &ns1__GetLyricByID2Response);

	/// Web service operation 'AdminJPNGetRightsInfoByModifyID' (returns error code or SOAP_OK)
	virtual	int AdminJPNGetRightsInfoByModifyID_(_ns1__AdminJPNGetRightsInfoByModifyID *ns1__AdminJPNGetRightsInfoByModifyID, _ns1__AdminJPNGetRightsInfoByModifyIDResponse &ns1__AdminJPNGetRightsInfoByModifyIDResponse) { return this->AdminJPNGetRightsInfoByModifyID_(NULL, NULL, ns1__AdminJPNGetRightsInfoByModifyID, ns1__AdminJPNGetRightsInfoByModifyIDResponse); }
	virtual	int AdminJPNGetRightsInfoByModifyID_(const char *endpoint, const char *soap_action, _ns1__AdminJPNGetRightsInfoByModifyID *ns1__AdminJPNGetRightsInfoByModifyID, _ns1__AdminJPNGetRightsInfoByModifyIDResponse &ns1__AdminJPNGetRightsInfoByModifyIDResponse);

	/// Web service operation 'AdminJPNGetRightsInfoByLyricID' (returns error code or SOAP_OK)
	virtual	int AdminJPNGetRightsInfoByLyricID_(_ns1__AdminJPNGetRightsInfoByLyricID *ns1__AdminJPNGetRightsInfoByLyricID, _ns1__AdminJPNGetRightsInfoByLyricIDResponse &ns1__AdminJPNGetRightsInfoByLyricIDResponse) { return this->AdminJPNGetRightsInfoByLyricID_(NULL, NULL, ns1__AdminJPNGetRightsInfoByLyricID, ns1__AdminJPNGetRightsInfoByLyricIDResponse); }
	virtual	int AdminJPNGetRightsInfoByLyricID_(const char *endpoint, const char *soap_action, _ns1__AdminJPNGetRightsInfoByLyricID *ns1__AdminJPNGetRightsInfoByLyricID, _ns1__AdminJPNGetRightsInfoByLyricIDResponse &ns1__AdminJPNGetRightsInfoByLyricIDResponse);

	/// Web service operation 'AdminJPNSetRightsInfo' (returns error code or SOAP_OK)
	virtual	int AdminJPNSetRightsInfo_(_ns1__AdminJPNSetRightsInfo *ns1__AdminJPNSetRightsInfo, _ns1__AdminJPNSetRightsInfoResponse &ns1__AdminJPNSetRightsInfoResponse) { return this->AdminJPNSetRightsInfo_(NULL, NULL, ns1__AdminJPNSetRightsInfo, ns1__AdminJPNSetRightsInfoResponse); }
	virtual	int AdminJPNSetRightsInfo_(const char *endpoint, const char *soap_action, _ns1__AdminJPNSetRightsInfo *ns1__AdminJPNSetRightsInfo, _ns1__AdminJPNSetRightsInfoResponse &ns1__AdminJPNSetRightsInfoResponse);

	/// Web service operation 'AdminJPNSearchRightsInfoList' (returns error code or SOAP_OK)
	virtual	int AdminJPNSearchRightsInfoList_(_ns1__AdminJPNSearchRightsInfoList *ns1__AdminJPNSearchRightsInfoList, _ns1__AdminJPNSearchRightsInfoListResponse &ns1__AdminJPNSearchRightsInfoListResponse) { return this->AdminJPNSearchRightsInfoList_(NULL, NULL, ns1__AdminJPNSearchRightsInfoList, ns1__AdminJPNSearchRightsInfoListResponse); }
	virtual	int AdminJPNSearchRightsInfoList_(const char *endpoint, const char *soap_action, _ns1__AdminJPNSearchRightsInfoList *ns1__AdminJPNSearchRightsInfoList, _ns1__AdminJPNSearchRightsInfoListResponse &ns1__AdminJPNSearchRightsInfoListResponse);

	/// Web service operation 'AdminLoginRightsJPN' (returns error code or SOAP_OK)
	virtual	int AdminLoginRightsJPN_(_ns1__AdminLoginRightsJPN *ns1__AdminLoginRightsJPN, _ns1__AdminLoginRightsJPNResponse &ns1__AdminLoginRightsJPNResponse) { return this->AdminLoginRightsJPN_(NULL, NULL, ns1__AdminLoginRightsJPN, ns1__AdminLoginRightsJPNResponse); }
	virtual	int AdminLoginRightsJPN_(const char *endpoint, const char *soap_action, _ns1__AdminLoginRightsJPN *ns1__AdminLoginRightsJPN, _ns1__AdminLoginRightsJPNResponse &ns1__AdminLoginRightsJPNResponse);

	/// Web service operation 'GetSearchLyricCount' (returns error code or SOAP_OK)
	virtual	int GetSearchLyricCount_(_ns1__GetSearchLyricCount *ns1__GetSearchLyricCount, _ns1__GetSearchLyricCountResponse &ns1__GetSearchLyricCountResponse) { return this->GetSearchLyricCount_(NULL, NULL, ns1__GetSearchLyricCount, ns1__GetSearchLyricCountResponse); }
	virtual	int GetSearchLyricCount_(const char *endpoint, const char *soap_action, _ns1__GetSearchLyricCount *ns1__GetSearchLyricCount, _ns1__GetSearchLyricCountResponse &ns1__GetSearchLyricCountResponse);

	/// Web service operation 'AdminLoginLyricMonitor' (returns error code or SOAP_OK)
	virtual	int AdminLoginLyricMonitor_(_ns1__AdminLoginLyricMonitor *ns1__AdminLoginLyricMonitor, _ns1__AdminLoginLyricMonitorResponse &ns1__AdminLoginLyricMonitorResponse) { return this->AdminLoginLyricMonitor_(NULL, NULL, ns1__AdminLoginLyricMonitor, ns1__AdminLoginLyricMonitorResponse); }
	virtual	int AdminLoginLyricMonitor_(const char *endpoint, const char *soap_action, _ns1__AdminLoginLyricMonitor *ns1__AdminLoginLyricMonitor, _ns1__AdminLoginLyricMonitorResponse &ns1__AdminLoginLyricMonitorResponse);

	/// Web service operation 'AdminGetLyrics' (returns error code or SOAP_OK)
	virtual	int AdminGetLyrics_(_ns1__AdminGetLyrics *ns1__AdminGetLyrics, _ns1__AdminGetLyricsResponse &ns1__AdminGetLyricsResponse) { return this->AdminGetLyrics_(NULL, NULL, ns1__AdminGetLyrics, ns1__AdminGetLyricsResponse); }
	virtual	int AdminGetLyrics_(const char *endpoint, const char *soap_action, _ns1__AdminGetLyrics *ns1__AdminGetLyrics, _ns1__AdminGetLyricsResponse &ns1__AdminGetLyricsResponse);

	/// Web service operation 'AdminDeleteLyrics' (returns error code or SOAP_OK)
	virtual	int AdminDeleteLyrics_(_ns1__AdminDeleteLyrics *ns1__AdminDeleteLyrics, _ns1__AdminDeleteLyricsResponse &ns1__AdminDeleteLyricsResponse) { return this->AdminDeleteLyrics_(NULL, NULL, ns1__AdminDeleteLyrics, ns1__AdminDeleteLyricsResponse); }
	virtual	int AdminDeleteLyrics_(const char *endpoint, const char *soap_action, _ns1__AdminDeleteLyrics *ns1__AdminDeleteLyrics, _ns1__AdminDeleteLyricsResponse &ns1__AdminDeleteLyricsResponse);

	/// Web service operation 'AdminGetLatestLyricID' (returns error code or SOAP_OK)
	virtual	int AdminGetLatestLyricID_(_ns1__AdminGetLatestLyricID *ns1__AdminGetLatestLyricID, _ns1__AdminGetLatestLyricIDResponse &ns1__AdminGetLatestLyricIDResponse) { return this->AdminGetLatestLyricID_(NULL, NULL, ns1__AdminGetLatestLyricID, ns1__AdminGetLatestLyricIDResponse); }
	virtual	int AdminGetLatestLyricID_(const char *endpoint, const char *soap_action, _ns1__AdminGetLatestLyricID *ns1__AdminGetLatestLyricID, _ns1__AdminGetLatestLyricIDResponse &ns1__AdminGetLatestLyricIDResponse);
};
#endif
